version: '3'
services:
  bastion:
    image: bastion-on-fargate:latest
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    command: >
      /usr/bin/sh -c
        "amazon-ssm-agent -register -code $${SSM_AGENT_CODE} -id $${SSM_AGENT_ID} -region ap-northeast-1 && \
        amazon-ssm-agent"
